name: Sync to Deploy Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Push to deploy repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_REPO_TOKEN }}
        with:
          source-directory: "."
          destination-github-username: "mohitvijayv"
          destination-repository-name: "designer-portfolio-mahima"
          target-branch: main
          user-email: github-actions[bot]@users.noreply.github.com
          user-name: github-actions[bot]
